export const SELECT_CURRENT_LANGUAGE = 'SELECT_CURRENT_LANGUAGE';
export const LOADING_LANGUAGES = 'LOADING_LANGUAGES';
export const LANGUAGES_COMPLETED = 'LANGUAGES_COMPLETED';
export const LANGUAGES_FAILED = 'LANGUAGES_FAILED';